pipeline{
     agent { label 'MyNode' }
stages {
        stage ('Clone') {
            steps {
                git branch: 'main', url: "https://github.com/hossain109/CICDMavenProject.git"
            }
        }
     
        stage("Buil") {
            steps {
              build 'https://github.com/hossain109/Jenkins-CI-CD.git'
            }
        }
      }
}