pipeline{
     agent { label 'MyNode' }
stages {
        stage ('Clone') {
            steps {
                git branch: 'main', url: "https://github.com/hossain109/CICDMavenProject.git"
            }
        }
     
       stage('Compile') {
            steps {
                script {
                    withMaven(maven: 'M3') {
                        sh 'mvn clean compile'
                    }
                }
            }
         }
      stage('Test') {
            steps {
                script {
                    withMaven(maven: 'M3') {
                        sh 'mvn test'
                    }
                }
           }
      }
              stage('Test') {
            steps {
                script {
                    withMaven(maven: 'M3') {
                        sh 'mvn test'
                    }
                }
 }
}