pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
  stages {
    stage('Deploy') {
      steps {
        sh 'kubectl apply -f deploy.yml'
      }
    }
  }
  stages {
    stage('build') {
      steps {
        sh 'node --version'
      }
    }
  }
}
